services:
  maindb:
    image: postgres:12
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      
  bank-system:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@maindb:5432/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - CURRENCY_API_KEY=${CURRENCY_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - maindb

volumes:
  data: